#!/bin/env bash

export GYINST=1

if [ "$1" == "--move-only" ]; then
    MOVE_ONLY=1
    shift
fi

if [ "$1" == "-e" ]; then
    UNINSTALL=1
    shift
fi

if [ $# -eq 0 ]; then
    if [ -e .git ]; then
        target=$(basename $PWD)
        cd ..
    else
        echo "FATAL: No arguments provided." >&2
        exit 1
    fi
elif [ $# -gt 1 ]; then
    echo "FATAL: Too many arguments provided." >&2
    exit 1
else
    target=$1
fi

if [ ! -e /data/data/com.termux/files -o -r / ];then
    R=
	if [ ! -e '/bin/env' ]; then
		sudo ln -sf /usr/bin/env /bin
	fi
else # termux
    R="/data/data/com.termux/files/usr"
	if [ ! -e /data/data/com.termux/files/usr/usr ];then
		ln -sf /data/data/com.termux/files/usr /data/data/com.termux/files/usr/usr
    fi
    if [ ! -L /data/data/com.termux/files/usr/home ];then
		cp -a /data/data/com.termux/files/usr/home/* /data/data/com.termux/files/home
		rm -rf /data/data/com.termux/files/usr/home
		ln -sf /data/data/com.termux/files/home /data/data/com.termux/files/usr/home
    fi
    if [ ! -e /data/data/com.termux/files/usr/local ];then
		ln -sf /data/data/com.termux/files/usr /data/data/com.termux/files/usr/local
	fi
	if [ ! -e /data/data/com.termux/files/usr/bin/sudo ];then
		cat - > /data/data/com.termux/files/usr/bin/sudo <<END
#!/bin/env bash
exec $@
END
        chmod +x /data/data/com.termux/files/usr/bin/sudo
    fi
fi


function user_do() {
    if [ -n "$SUDO_USER" ]; then
        sudo -u $SUDO_USER $@
    else
        $@
    fi
}

if [ -e $R/var/lib/git_project/$target ]; then
    echo "FATAL: $R/var/lib/git_project/$target already exists." >&2
    exit 1
fi

mkdir -p $R/var/lib/git_project/tmp

if [ -e $target/.git ]; then
    mv $target $R/var/lib/git_project
else
    mkdir -p $R/var/lib/git_project/$target
    chmod 777 $R/var/lib/git_project/tmp
    cd $R/var/lib/git_project/tmp
    user_do git clone https://github.com/Yougain/$target
    if [ ! -e $target ]; then
        echo "FATAL: cannot git clone https://github.com/Yougain/$target."
        exit 1
    fi
    mv $target ../
    cd ../$target
fi

  
user_do bash <<END
    mkdir -p ~/git_project
    ln -s $R/var/lib/git_project/$target ~/git_project/$target
    if [ -z "$MOVE_ONLY" ]; then
        if [ -e ~/git_project/$target/install ]; then
            ~/git_project/$target/install
        fi
    fi
END


