#!/bin/env bash

cd $(dirname $0)


. ./gy_install $0

#sudo $IST update -y
#if [ "$IST" = "apt-get" ];then
#	sudo DEBIAN_FRONTEND=noninteractive $IST -y upgrade -yq
#else
#	sudo $IST upgrade -y
#fi

#sudo $IST install -y sudo git

install gy_install
ln -s gy_install gy_uninstall

install_lines .zshrc .bashrc <<END
    for i in /etc/shrc.d/*.sh; do
        if [ "\$i" = "/etc/shrc.d/*.sh" ]; then
            break
        fi
        if [ -r "\$i" ]; then
            . "\$i"
        fi
    done
    unset i
END

install_lines .bashrc <<END
    for i in /etc/bashrc.d/*.sh; do
        if [ "\$i" = "/etc/bashrc.d/*.sh" ]; then
            break
        fi
        if [ -r "\$i" ]; then
            . "\$i"
        fi
    done
    unset i
END


install %wsl.sh %local_path.sh /etc/shrc.d
install dbv.bash /lib/gy_support

install_lines /etc/bashrc.d/%dbv.bash <<END
    export BASH_ENV=/lib/gy_support/dbv.bash
END


