#!/bin/env bash


script_path="${BASH_SOURCE[0]}"
script_name="$(basename -- "$script_path")"
script_dir="$(cd -- "$(dirname -- "$script_path")" && pwd)"

cd $script_dir

. ./gy_install $0

#sudo $IST update -y
#if [ "$IST" = "apt-get" ];then
#	sudo DEBIAN_FRONTEND=noninteractive $IST -y upgrade -yq
#else
#	sudo $IST upgrade -y
#fi

#sudo $IST install -y sudo git

install gy_install gyinst
ln -s gy_install gy_uninstall

install_lines .zshrc <<END
    setopt NONOMATCH
END


install_lines .bashrc <<END
    shopt -s nullglob
END


install_lines .bashrc <<END
    export YK_PREFIX=\$(dirname /lib)
    for i in \$(printf '%s\n' /etc/shrc.d/*.sh | LC_ALL=C sort); do
        if [ "\$i" = "/etc/shrc.d/*.sh" ]; then
            break
        fi
        if [ -r "\$i" ]; then
            . "\$i"
        fi
    done
    unset i
    for i in \$(printf '%s\n' /etc/bashrc.d/*.bash | LC_ALL=C sort); do
        if [ "\$i" = "/etc/bashrc.d/*.bash" ]; then
            break
        fi
        if [ -r "\$i" ]; then
            . "\$i"
        fi
    done
    unset i
END


install_lines .zshrc <<END
    export YK_PREFIX=\$(dirname /lib)
    for i in \$(print -rl -- /etc/shrc.d/*.sh | LC_ALL=C sort); do
        if [ "\$i" = "/etc/shrc.d/*.sh" ]; then
            break
        fi
        if [ -r "\$i" ]; then
            . "\$i"
        fi
    done
    unset i
    for i in \$(print -rl -- /etc/zshrc.d/*.zsh | LC_ALL=C sort); do
        if [ "\$i" = "/etc/zshrc.d/*.zsh" ]; then
            break
        fi
        if [ -r "\$i" ]; then
            . "\$i"
        fi
    done
    unset i
END



install %wsl.sh %local_path.sh /etc/shrc.d
install dbv.bash /lib/gy_support
install %%dbv.zsh /etc/zshrc.d

install_lines /etc/shrc.d/%dbv.sh <<END
    export BASH_ENV=/lib/gy_support/dbv.bash
END


install_lines .zshrc <<END
    setopt NOMATCH
END

install_lines .bashrc <<END
    shopt -s failglob
END

